---

networks:
  default:
      name: example.com

services:

  control:
    container_name: control
    hostname: control
    image: quay.io/tonykay/vmlet-rhel-8-control
    ports:
      - "22"
    privileged: true
    environment:
      - SSH_DIR_SOURCE=https://github.com/tonykay/classroom-multi/raw/main/builds/dojo.tar.gz
    
  frontend:
    container_name: frontend
    hostname: frontend
    image: vmlet-rhel-8
    ports:
      - "22"
      - "8080:80"
    privileged: true

  app-01:
    container_name: app-01
    hostname: app-01
    image: quay.io/tonykay/vmlet-rhel-8
    ports:
      - "22"
    privileged: true

  app-02:
    container_name: app-02
    hostname: app-02
    image: quay.io/tonykay/vmlet-rhel-8
    ports:
      - "22"
    privileged: true

  appdb1:
    container_name: appdb1
    hostname: appdb1
    image: quay.io/tonykay/vmlet-rhel-8
    ports:
      - "22"
    privileged: true

  terminal:
    container_name: terminal
    hostname: terminal
    image: quay.io/openshifthomeroom/workshop-terminal:latest
    ports:
      - "10080:10080"
    volumes:
      - "../bind_mounts/ssh:/opt/app-root/src/.ssh:z,ro"

  classroom-httpd:
    container_name: classroom-httpd
    hostname: classroom-httpd
    image: quay.io/tonykay/classroom-rhel-8-httpd
    privileged: true
    environment:
      - WWW_DIR_SOURCE=https://github.com/tonykay/classroom-multi/raw/main/builds/dojo.tar.gz
    ports:
      - "80:8080"
        
...
